default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: kakeibo
production:
  <<: *default
  database: kakeibo_production